language: php
php:
  - 5.5
  - 5.4
install: "./bin/install"

after_script:
  - php ./vendor/bin/coveralls

script: ./test/run

notifications:
  email:
    recipients:
      - mailbot@brightflair.com
    on_success: always
    on_failure: always